name: Get version
description: Get version of godot from version.py

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: bend-n/godot-builds/.github/actions/setup@main
      with:
        ref: ${{ env.ref }}

    - name: Get version
      run: |
        cd godot
        echo 'print(f"{major}.{minor}")' >> version.py
        echo "version-name=$(python version.py)" >> $GITHUB_ENV
        version=$(python version.py)

        git checkout version.py

        echo 'print(status)' >> version.py
        echo "release=$(python version.py)" >> $GITHUB_ENV
        release=$(python version.py)

        release_name="$version"
        [[ ${release} == 'stable' ]] || release_name+=${release}
        echo "release-name=$release_name" >> $GITHUB_ENV
      shell: bash

    - name: Post get version
      if: always()
      run: rm -rf godot
      shell: bash
